### ISSUE TITLE
MAP View

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/rbsc_drupal_versailles#12]
Build a map view using Leaflet.js overlay on historic Versailles map. Need to map Geographic categories to region on map before beginning this.

**Comment by sdellis** [comment]
Just to have this info all in one place and out of email...
[Demo](http://eliotjordan.github.io/versailles-demo/dist/index.html)
[Demo.json](https://gist.githubusercontent.com/sdellis/8e16c57718a9b99cac53/raw/9b4a3f76ad00cf94c1fc2abe187031dfe50d4d17/gistfile1.json)
[Sections](https://gist.github.com/sdellis/b7dbbea97cca6f8c5af7)

**Comment by sdellis** [comment]
Items should have a "Locate on Map" link, or should have the map next to the item in the detail view, with the item location highlighted/pinned on the map.
