### ISSUE TITLE
Add "Next" and "Previous" buttons for navigating between section items

### ISSUE THREAD

**Issue by sdellis** [pulibrary/rbsc_drupal_versailles#15]
add forward/back buttons allowing to navigate directly from one item of a section to the next, rather than having to go back to the section page and scroll down

**Comment by kevinreiss** [comment]
Perhaps writing a function that is embedded in a node template for the "item" content type could be an easy way to do this.

**Comment by sdellis** [comment]
@kevinreiss - That tip was very helpful!  This is basically fixed, although, some items' sort order is only relevant in the context of their cases, not the exhibit.  More logic could probably be added to do case-by-case queries, and if there's no next or previous, query for the appropriate case.  Or, the exhibition sort order could be reset for the few items that are out of order.

**Comment by sdellis** [comment]
This is now scoped to the case.  I will discuss any other necessary features tomorrow in the meeting.
