### ISSUE TITLE
Use Media Object View Mode in Contributor Detail view

### ISSUE THREAD

**Issue by sdellis** [pulibrary/rbsc_drupal_versailles#16]
Example:
http://libphp-dev.princeton.edu/versailles/contributor/baudet-etienne-ca-1638%E2%80%931711

Currently uses old image link field and links to the image browser, not the content.   This view uses aggregation for exhibit items.  Not sure if one can use rendered view modes with aggregation.

**Comment by kevinreiss** [comment]
I am not really sure why I was using aggregation on this view. I turned it off and flipped to using the IIIF image field and it seemed to work out well. This view is using "fields" so I don't think you can use view modes at all. You can only use any formatters that have been defined for the field, these would be the values available in the "manage display" tab of a field's definition. For the view to use "view modes" the "Show" value in the view configuration I think the would need to flip to "rendered entity" or "content".
