### ISSUE TITLE
map view missing image and orientation fixes

### ISSUE THREAD

**Issue by sdellis** [pulibrary/rbsc_drupal_versailles#39]
[Item 910](http://versailles-local.princeton.edu/versailles/item/910) shows a broken image link in the map view (one of the 9 items in the A location).

I also noticed that since I manually rotated the original images, the rotation is not getting updated in the map.  All images should have rotation set to zero at this point.

Tagging @eliotjordan too since I'm not sure whether or not @kevinreiss has had to deal with rotation issues in the map thumbs.

**Comment by kevinreiss** [comment]
Item 910 has no image id field. The map predates the IIIF field so it was looking there and not the iiif field.  Would the IDs of the images you cleaned up have changed in the image server? If so, than this is likely the image rotation issue as well. The map is looking at the old ID.
