### ISSUE TITLE
Overlay of the exhibition objects with the Versailles illustrated map

### ISSUE THREAD

**Issue by sdellis** [pulibrary/rbsc_drupal_versailles#9]
The clickable map will be an alternate way to browse the exhibit objects, intended to create an understanding of where and when the objects resided at Versailles. [Here is the map](http://diglib.princeton.edu/tools/ib/exhibits/Versailles/versailles_13) we will use.  @eliotjordan had some thoughts on how to best do that and is going to assist us with it.

**Comment by eliotjordan** [comment]
@sdellis @kevinreiss Here's a demo for the Versailles map. I picked data for the first two objects from each "section".

http://eliotjordan.github.io/versailles-demo/dist/index.html
https://github.com/eliotjordan/versailles-demo

 A few things:
- Styles, icons, markers are set to the default and can be changed.
- A number of images are rotated 90 degrees from their actual orientation. They're a real PITA. Maybe the original jp2 should be rotated?
- I can't find section M on the photo.

**Comment by jpstroop** [comment]
Looks really cool!

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
@eliotjordan do you think this sort of output will work? 

http://libphp-prod.princeton.edu/versailles/map.json

@sdellis I put the site up on the production server running the "geojson_demo" branch. I did add the coordinates as lat/long fields attached to the geographic sections taxonomy.

**Comment by eliotjordan** [comment]
@kevinreiss I update the demo to reflect this new format (not pulling from the server just yet). There are a few issues.

1. There is a 'null' value where, I presume, an item record should be. This creates invalid geojson.
````javascript
        "nid": 886,
        "field_image_id": "http://libimages.princeton.edu/loris/exhibits%2...",
        "field_ver_geographic_section": "L"
      }
    },
    null,
    {
      "type": "Feature",
````
2. Some of the items have null image id values.
```javascript
"field_image_id": null,
````

**Comment by eliotjordan** [comment]
@kevinreiss Also. One of the properties should contain rotation data for the thumbnails show up the correct direction.

**Comment by kevinreiss** [comment]
Okay. http://libphp-prod.princeton.edu/versailles/map.json should now be a valid JSON file. The null row was due to the one geographic section marked "M" that could not be placed on the map. What would be the coordinates to use to place a marker at the bottom left corner?

**Comment by eliotjordan** [comment]
@kevinreiss Here's the location for section M:

lat: -141
lng: 167.125

**Comment by eliotjordan** [comment]
@kevinreiss Default val for rotation should be set to 0 instead of whitespace.

**Comment by eliotjordan** [comment]
@kevinreiss @sdellis I pushed a [new demo](http://eliotjordan.github.io/versailles-demo/dist/live-demo.html) that slurps live data from the server. Because of CORS, you need a plugin to view. [CORS Toggle](https://chrome.google.com/webstore/detail/cors-toggle/omcncfnpmcabckcddookmnajignpffnh?hl=en) is a nice one for Chrome.

**Comment by eliotjordan** [comment]
New [icon](http://commons.wikimedia.org/wiki/File:Fleur_de_lys_du_qu%C3%A9bec.svg)?

![](http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Fleur_de_lys_du_qu%C3%A9bec.svg/200px-Fleur_de_lys_du_qu%C3%A9bec.svg.png)

**Comment by kevinreiss** [comment]
Quick question @eliotjordan. Any reason the markers fall into an odd distribution rather than just appearing in the circle?

See:

https://www.dropbox.com/s/e8quq7487tqri9f/Screenshot%202015-01-18%2012.59.23.png?dl=0

This is geo-point "A" http://libphp-dev.princeton.edu/versailles/geographic-sections/a

**Comment by kevinreiss** [comment]
The map is very nice but I do think we need to give the users some context and way to make sense of the various points on the maps. Though the curators said the points have no real meaning it seems to me coming up a brief descriptive label for each of the A-M sections is needed to give them map display some context. Those can be rendered in a list next to the map. Each item in the list should take you to the proper point on the map when clicked.

**Comment by eliotjordan** [comment]
@kevinreiss Not sure. A beahvior of the marker cluster plugin probably. Perhaps increasing the [spiderfyDistanceMultiplier](https://github.com/eliotjordan/versailles-demo/blob/master/app/scripts/main.js#L96) would help.

**Comment by eliotjordan** [comment]
@kevinreiss Just checked, distance multiplier changes don't alter that behavior. There are a lot of points at the same "location" in some of these areas, and the spiral effect allows the plugin to pack them together without creating a circle with a huge radius.

**Comment by kevinreiss** [comment]
Thanks for the update.

**Comment by sdellis** [comment]
The map looks great, guys!
